# BASIC CALCULATOR PROGRAM

# USER INPUT
NUM1 = FLOAT(INPUT("ENTER THE FIRST NUMBER: "))
NUM2 = FLOAT(INPUT("ENTER THE SECOND NUMBER: "))

# USER INPUT FOR OPERATION
OPERATION = INPUT("ENTER OPERATION (+, -, *, /): ")

# PERFORM THE CALCULATION
IF OPERATION == "+":
    RESULT = NUM1 + NUM2
    PRINT(F"{NUM1} + {NUM2} = {RESULT}")
ELIF OPERATION == "-":
    RESULT = NUM1 - NUM2
    PRINT(F"{NUM1} - {NUM2} = {RESULT}")
ELIF OPERATION == "*":
    RESULT = NUM1 * NUM2
    PRINT(F"{NUM1} * {NUM2} = {RESULT}")
ELIF OPERATION == "/":
    IF NUM2 != 0:
        RESULT = NUM1 / NUM2
        PRINT(F"{NUM1} / {NUM2} = {RESULT}")
    ELSE:
        PRINT("ERROR: DIVISION BY ZERO IS NOT ALLOWED.")
ELSE:
    PRINT("INVALID OPERATION. PLEASE ENTER ONE OF: +, -, *, /")
